name: backend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:     
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        functions: [Edna.AssignmentLearnContent, Edna.AssignmentLinks, Edna.Assignments, Edna.Connect, Edna.Platforms, Edna.Users]
    env:
      PROJECTS: ${{ github.workspace }}\backend\Functions\**\*.csproj
      OUTPUT_DIR: ${{ github.workspace }}\.output
      DOTNET_VERSION: "3.1.101"
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install dependencies
      run: dotnet restore ${{ env.PROJECTS }}
    - name: Build
      run: dotnet build ${{ env.PROJECTS }} --configuration Release --no-restore
